---
build_from:
  amd64: ghcr.io/hassio-addons/debian-base/amd64:5.3.1
  armhf: ghcr.io/hassio-addons/debian-base/armhf:5.3.1
  armv7: ghcr.io/hassio-addons/debian-base/armv7:5.3.1
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:5.3.1
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@degatano.com
