---
build_from:
  amd64: ghcr.io/hassio-addons/debian-base/amd64:6.2.7
  armhf: ghcr.io/hassio-addons/debian-base/armhf:6.2.7
  armv7: ghcr.io/hassio-addons/debian-base/armv7:6.2.7
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:6.2.7
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@degatano.com
