---
build_from:
  amd64: ghcr.io/hassio-addons/debian-base/amd64
  armhf: ghcr.io/hassio-addons/debian-base/armhf
  armv7: ghcr.io/hassio-addons/debian-base/armv7
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64
